"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {Copy,Plus,Save,Trash2} from "lucide-react";
import {brl} from "@/lib/format";
import {createClient} from "@/lib/supabase/client";
import type {TransactionItem} from "@/components/transaction-history";

type BudgetRow={id:string,categoryId:string,name:string,budgeted:number};
type DbRow={id:string,budgeted:number|string,transaction_categories:{id:string,name:string}|null};
const monthName=(month:string)=>new Date(`${month}-02T12:00:00`).toLocaleDateString("pt-BR",{month:"long",year:"numeric"});

export function BudgetManager({householdId,txs}:{householdId:string,txs:TransactionItem[]}){
 const [month,setMonth]=useState("2026-09"),[budgetId,setBudgetId]=useState(""),[rows,setRows]=useState<BudgetRow[]>([]),[loading,setLoading]=useState(true),[name,setName]=useState(""),[amount,setAmount]=useState(""),[message,setMessage]=useState(""),[confirmId,setConfirmId]=useState("");
 const load=useCallback(async()=>{if(!householdId)return;setLoading(true);const sb=createClient(),date=`${month}-01`;const {data:budget}=await sb.from("monthly_budgets").select("id").eq("household_id",householdId).eq("month",date).eq("name","Orçamento mensal").maybeSingle();if(!budget){setBudgetId("");setRows([]);setLoading(false);return}setBudgetId(budget.id);const {data}=await sb.from("budget_categories").select("id,budgeted,transaction_categories(id,name)").eq("budget_id",budget.id).order("created_at");setRows(((data??[]) as unknown as DbRow[]).map(r=>({id:r.id,categoryId:r.transaction_categories?.id||"",name:r.transaction_categories?.name||"Categoria",budgeted:Number(r.budgeted)})));setLoading(false)},[householdId,month]);
 useEffect(()=>{queueMicrotask(()=>void load())},[load]);
 useEffect(()=>{if(!budgetId)return;const sb=createClient(),channel=sb.channel(`budget-${budgetId}`).on("postgres_changes",{event:"*",schema:"public",table:"budget_categories",filter:`budget_id=eq.${budgetId}`},()=>void load()).subscribe();return()=>{void sb.removeChannel(channel)}},[budgetId,load]);
 const spentByCategory=useMemo(()=>txs.filter(t=>t.type==="expense"&&t.date.startsWith(month)).reduce<Record<string,number>>((a,t)=>(a[t.category]=(a[t.category]||0)+t.amount,a),{}),[txs,month]);
 const total=rows.reduce((s,r)=>s+r.budgeted,0),spent=Object.values(spentByCategory).reduce((s,v)=>s+v,0);
 async function ensureBudget(){if(budgetId)return budgetId;const sb=createClient(),{data,error}=await sb.from("monthly_budgets").insert({household_id:householdId,month:`${month}-01`,name:"Orçamento mensal",total_limit:0,separate_project:false}).select("id").single();if(error)throw error;setBudgetId(data.id);return data.id}
 async function add(){const value=Number(amount.replaceAll(".","").replace(",","."));if(!name.trim()||!value||value<0){setMessage("Informe o nome e o limite da categoria.");return}try{const sb=createClient(),id=await ensureBudget();const {data:category,error:catError}=await sb.from("transaction_categories").upsert({household_id:householdId,name:name.trim(),kind:"expense",active:true},{onConflict:"household_id,name,kind"}).select("id").single();if(catError)throw catError;const {error}=await sb.from("budget_categories").upsert({household_id:householdId,budget_id:id,category_id:category.id,budgeted:value},{onConflict:"budget_id,category_id"});if(error)throw error;setName("");setAmount("");setMessage("Categoria adicionada.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível adicionar.")}}
 async function saveRow(row:BudgetRow){const sb=createClient(),{error}=await sb.from("budget_categories").update({budgeted:row.budgeted}).eq("id",row.id);if(error){setMessage(error.message);return}await sb.from("monthly_budgets").update({total_limit:rows.reduce((s,r)=>s+r.budgeted,0)}).eq("id",budgetId);setMessage(`${row.name} atualizado.`)}
 async function remove(row:BudgetRow){if(confirmId!==row.id){setConfirmId(row.id);return}const sb=createClient(),{error}=await sb.from("budget_categories").delete().eq("id",row.id);if(error){setMessage(error.message);return}setRows(v=>v.filter(x=>x.id!==row.id));setConfirmId("");setMessage("Categoria removida deste mês.")}
 async function copyPrevious(){try{const sb=createClient(),target=await ensureBudget();const {data:previous}=await sb.from("monthly_budgets").select("id").eq("household_id",householdId).eq("name","Orçamento mensal").lt("month",`${month}-01`).order("month",{ascending:false}).limit(1).maybeSingle();if(!previous){setMessage("Não existe orçamento anterior para copiar.");return}const {data:previousRows}=await sb.from("budget_categories").select("category_id,budgeted").eq("budget_id",previous.id);if(previousRows?.length){const {error}=await sb.from("budget_categories").upsert(previousRows.map(r=>({household_id:householdId,budget_id:target,category_id:r.category_id,budgeted:r.budgeted})),{onConflict:"budget_id,category_id"});if(error)throw error}setMessage("Categorias copiadas do mês anterior.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível copiar.")}}
 return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="label">Orçamento configurável</p><h2 className="text-3xl font-black capitalize">{monthName(month)}</h2></div><label><span className="label">Selecionar mês</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="tap mt-1 block rounded-xl border bg-white px-3"/></label></div><div className="mt-5 grid grid-cols-3 gap-3"><Summary label="Limite" value={total}/><Summary label="Gasto real" value={spent}/><Summary label="Restante" value={total-spent}/></div>{loading?<p className="mt-6 text-sm">Carregando orçamento…</p>:rows.length?<div className="mt-5 grid gap-3 md:grid-cols-2">{rows.map(row=>{const used=spentByCategory[row.name]||0,pct=row.budgeted?Math.round(used/row.budgeted*100):0;return <article className="card p-4" key={row.id}><div className="flex items-center gap-2"><h3 className="flex-1 font-black">{row.name}</h3><button onClick={()=>void remove(row)} className={`tap rounded-lg p-2 ${confirmId===row.id?"bg-red-600 text-white":"text-red-700"}`} aria-label={confirmId===row.id?"Confirmar exclusão":"Remover categoria"}><Trash2 size={16}/></button></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-ink/10"><div className={`h-full ${pct>100?"bg-red-500":pct>80?"bg-amber-400":"bg-ink"}`} style={{width:`${Math.min(pct,100)}%`}}/></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><label>Orçado<input type="number" min="0" step="0.01" value={row.budgeted} onChange={e=>setRows(v=>v.map(x=>x.id===row.id?{...x,budgeted:Number(e.target.value)}:x))} className="mt-1 w-full rounded-lg border px-2 py-2 font-bold"/></label><span>Gasto<br/><b>{brl(used)}</b></span><span>Restante<br/><b>{brl(row.budgeted-used)}</b></span></div><button onClick={()=>void saveRow(row)} className="tap mt-3 flex items-center gap-1 text-xs font-bold"><Save size={14}/> Salvar limite</button></article>})}</div>:<div className="card mt-5 p-5 text-center"><p className="font-bold">Este mês ainda não possui categorias.</p><button onClick={()=>void copyPrevious()} className="tap mt-4 inline-flex items-center gap-2 rounded-xl bg-ink px-4 text-sm font-bold text-white"><Copy size={16}/> Copiar mês anterior</button></div>}<section className="card mt-5 p-5"><h3 className="font-black">Adicionar categoria</h3><div className="mt-3 grid gap-3 sm:grid-cols-[1fr_180px_auto]"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da categoria" className="tap rounded-xl border px-3"/><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="Limite em R$" className="tap rounded-xl border px-3"/><button onClick={()=>void add()} className="tap flex items-center justify-center gap-2 rounded-xl bg-lime px-4 font-black"><Plus size={17}/> Adicionar</button></div>{message&&<p role="status" className="mt-3 rounded-xl bg-mint p-3 text-sm">{message}</p>}</section></div>
}

function Summary({label,value}:{label:string,value:number}){return <div className="card p-4"><p className="label">{label}</p><p className="money mt-2 text-lg font-black sm:text-2xl">{brl(value)}</p></div>}
