"use client";
import {useMemo,useState} from "react";
import {CreditCard,Plus,Trash2,X} from "lucide-react";
import {brl} from "@/lib/format";
import {createClient} from "@/lib/supabase/client";
import type {TransactionItem} from "@/components/transaction-history";

export type CardItem={id:string,name:string,limit:number,closingDay:number,dueDay:number,active:boolean};
const invoiceMonth=(date:string,closing:number)=>{const d=new Date(`${date}T12:00:00`);if(d.getDate()>closing)d.setMonth(d.getMonth()+1);return d.toISOString().slice(0,7)};
const localDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo"}).format(new Date());

export function CreditCards({householdId,cards,txs,reload}:{householdId:string,cards:CardItem[],txs:TransactionItem[],reload:()=>Promise<void>}){
 const [month,setMonth]=useState(localDate().slice(0,7)),[name,setName]=useState(""),[limit,setLimit]=useState(""),[closing,setClosing]=useState("17"),[due,setDue]=useState("22"),[message,setMessage]=useState(""),[showForm,setShowForm]=useState(false),[purchaseCard,setPurchaseCard]=useState<CardItem|null>(null);
 const cardTransactions=useMemo(()=>Object.fromEntries(cards.map(card=>[card.id,txs.filter(t=>t.type==="expense"&&t.cardId===card.id&&invoiceMonth(t.date,card.closingDay)===month).sort((a,b)=>a.date.localeCompare(b.date))])),[cards,txs,month]);
 async function add(){const value=Number(limit.replaceAll(".","").replace(",","."));if(!name.trim()||!value){setMessage("Informe o nome e o limite do cartão.");return}const {error}=await createClient().from("credit_cards").insert({household_id:householdId,name:name.trim(),credit_limit:value,closing_day:Number(closing),due_day:Number(due),active:true});if(error){setMessage(error.message);return}setName("");setLimit("");setShowForm(false);setMessage("Cartão adicionado.");await reload()}
 async function remove(card:CardItem){const {error}=await createClient().from("credit_cards").update({active:false}).eq("id",card.id);if(error){setMessage(error.message);return}setMessage("Cartão arquivado.");await reload()}
 return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="label">Cartões de crédito</p><h2 className="text-3xl font-black">Faturas dinâmicas</h2></div><label><span className="label">Mês da fatura</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="tap mt-1 block rounded-xl border bg-white px-3"/></label></div>
  <div className="mt-5 grid gap-4 md:grid-cols-2">{cards.map(card=>{const purchases=cardTransactions[card.id]||[],total=purchases.reduce((sum,item)=>sum+item.amount,0),available=card.limit-total,pct=card.limit?total/card.limit*100:0;return <article className="rounded-3xl bg-ink p-5 text-white shadow-soft" key={card.id}><div className="flex items-start justify-between"><div><p className="text-xs text-white/55">Cartão</p><h3 className="text-2xl font-black">{card.name}</h3></div><CreditCard className="text-lime"/></div><p className="money mt-6 text-3xl font-black">{brl(total)}</p><p className="text-xs text-white/55">Fatura calculada pelos gastos registrados</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/15"><div className={`h-full ${pct>100?"bg-red-400":pct>80?"bg-amber-300":"bg-lime"}`} style={{width:`${Math.min(pct,100)}%`}}/></div><div className="mt-3 grid grid-cols-3 text-xs"><span>Limite<br/><b>{brl(card.limit)}</b></span><span>Disponível<br/><b>{brl(available)}</b></span><span>Fecha / vence<br/><b>{card.closingDay} / {card.dueDay}</b></span></div><button onClick={()=>setPurchaseCard(card)} className="tap mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-lime px-3 text-sm font-black text-ink"><Plus size={17}/> Registrar compra</button>{purchases.length>0&&<div className="mt-4 divide-y divide-white/10 border-t border-white/10">{purchases.map(item=><div key={item.id} className="flex justify-between gap-3 py-2 text-xs"><span className="min-w-0"><b className="block truncate">{item.description||item.category}</b><small className="text-white/50">{new Intl.DateTimeFormat("pt-BR",{timeZone:"UTC"}).format(new Date(`${item.date}T12:00:00Z`))}</small></span><b className="money shrink-0">{brl(item.amount)}</b></div>)}</div>}<button onClick={()=>void remove(card)} className="tap mt-2 flex items-center gap-1 text-xs text-white/60"><Trash2 size={14}/> Arquivar cartão</button></article>})}</div>
  {!cards.length&&<div className="card mt-5 p-6 text-center">Nenhum cartão ativo.</div>}<button onClick={()=>setShowForm(v=>!v)} className="tap mt-5 flex items-center gap-2 rounded-xl bg-lime px-4 font-black"><Plus size={18}/> Adicionar cartão</button>{showForm&&<section className="card mt-3 grid gap-3 p-5 sm:grid-cols-2"><label><span className="label">Nome</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Nubank" className="tap mt-1 w-full rounded-xl border px-3"/></label><label><span className="label">Limite</span><input value={limit} onChange={e=>setLimit(e.target.value)} inputMode="decimal" placeholder="R$ 0,00" className="tap mt-1 w-full rounded-xl border px-3"/></label><label><span className="label">Dia do fechamento</span><input type="number" min="1" max="31" value={closing} onChange={e=>setClosing(e.target.value)} className="tap mt-1 w-full rounded-xl border px-3"/></label><label><span className="label">Dia do vencimento</span><input type="number" min="1" max="31" value={due} onChange={e=>setDue(e.target.value)} className="tap mt-1 w-full rounded-xl border px-3"/></label><button onClick={()=>void add()} className="tap rounded-xl bg-ink p-3 font-black text-white sm:col-span-2">Salvar cartão</button></section>}
  {message&&<p role="status" className="mt-3 rounded-xl bg-mint p-3 text-sm">{message}</p>}<section className="card mt-5 p-5"><h3 className="font-black">Como a fatura é calculada?</h3><p className="mt-2 text-sm text-ink/60">Cada parcela entra somente na fatura do seu mês. Compras recorrentes ficam agendadas e aparecem no calendário financeiro.</p></section>{purchaseCard&&<PurchaseForm card={purchaseCard} close={()=>setPurchaseCard(null)} saved={text=>{setPurchaseCard(null);setMessage(text)}}/>}
 </div>
}

function PurchaseForm({card,close,saved}:{card:CardItem;close:()=>void;saved:(message:string)=>void}){
 const [description,setDescription]=useState(""),[amount,setAmount]=useState(""),[date,setDate]=useState(localDate()),[installments,setInstallments]=useState("1"),[recurring,setRecurring]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function save(){const value=Number(amount.replaceAll(".","").replace(",",".")),parts=Number(installments);if(!description.trim()||!value||parts<1){setError("Informe descrição, valor da parcela e quantidade.");return}if(recurring&&parts>1){setError("Escolha parcelada ou recorrente, não as duas opções.");return}setBusy(true);const {error:rpcError}=await createClient().rpc("register_credit_card_purchase",{target_card_id:card.id,purchase_description:description.trim(),installment_amount:value,purchase_date:date,installment_count:parts,make_recurring:recurring,request_group_id:crypto.randomUUID()});setBusy(false);if(rpcError){setError(rpcError.message);return}saved(parts>1?`${parts} parcelas registradas sem duplicação.`:recurring?"Compra registrada e recorrência mensal criada.":"Compra registrada na fatura.")}
 return <div className="fixed inset-0 z-50 flex items-end justify-center bg-ink/45 backdrop-blur-sm sm:items-center sm:p-4"><div className="w-full max-w-lg rounded-t-[2rem] bg-white p-5 sm:rounded-[2rem]"><div className="flex justify-between"><div><p className="label">Nova compra</p><h3 className="text-2xl font-black">Cartão {card.name}</h3></div><button onClick={close} className="tap grid w-12 place-items-center"><X/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Descrição</span><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ex.: assinatura ou loja" className="tap mt-1 w-full rounded-xl border px-3"/></label><label><span className="label">Valor de cada parcela</span><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="0,00" className="tap mt-1 w-full rounded-xl border px-3"/></label><label><span className="label">Data da compra</span><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="tap mt-1 w-full rounded-xl border px-3"/></label><label><span className="label">Quantidade de parcelas</span><input type="number" min="1" max="120" value={installments} disabled={recurring} onChange={e=>setInstallments(e.target.value)} className="tap mt-1 w-full rounded-xl border px-3 disabled:opacity-50"/></label><label className="flex items-center gap-2 rounded-xl bg-cream px-3"><input type="checkbox" checked={recurring} onChange={e=>{setRecurring(e.target.checked);if(e.target.checked)setInstallments("1")}}/><span className="text-sm font-bold">Cobrança recorrente mensal</span></label></div>{Number(installments)>1&&<p className="mt-3 rounded-xl bg-mint p-3 text-sm">Total da compra: <b>{brl((Number(amount.replaceAll(".","").replace(",","."))||0)*Number(installments))}</b>. Cada parcela ficará em seu respectivo mês.</p>}{error&&<p className="mt-3 text-sm font-bold text-red-700">{error}</p>}<button disabled={busy} onClick={()=>void save()} className="tap mt-4 w-full rounded-xl bg-ink p-3 font-black text-white disabled:opacity-50">{busy?"Registrando…":"Registrar sem duplicar"}</button></div></div>
}
