"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {ArrowLeft,CalendarDays,Check,ChevronLeft,ChevronRight,ExternalLink,Plus,Repeat2,Trash2,TrendingUp,X} from "lucide-react";
import {brl} from "@/lib/format";
import {createClient} from "@/lib/supabase/client";

type Income={id:string;description:string;amount:number|null;expected_on:string|null;income_class:string;status:string;notes:string|null};
type Event={id:string;title:string;starts_on:string;ends_on:string|null;amount:number|null;event_type:string;status:string};
type Recurring={id:string;description:string;amount:number|null;frequency:string;next_date:string|null;ends_on:string|null;active:boolean;type:string};
type Kind="income"|"event"|"recurring";
type Timeline={id:string;kind:Kind;title:string;amount:number|null;date:string;status:string;subtitle:string;raw:Income|Event|Recurring};
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo"}).format(new Date());
const money=(value:string)=>Number(value.replaceAll(".","").replace(",","."));
const monthLabel=(value:string)=>new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}-01T12:00:00Z`));
const dateLabel=(value:string)=>new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`));

export function FinancialCalendar({householdId,back}:{householdId:string;back:()=>void}){
 const [incomes,setIncomes]=useState<Income[]>([]),[events,setEvents]=useState<Event[]>([]),[recurring,setRecurring]=useState<Recurring[]>([]),[month,setMonth]=useState(today().slice(0,7)),[form,setForm]=useState<Kind|null>(null),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{if(!householdId)return;const sb=createClient(),[a,b,c]=await Promise.all([sb.from("planned_income").select("id,description,amount,expected_on,income_class,status,notes").eq("household_id",householdId).order("expected_on"),sb.from("financial_events").select("id,title,starts_on,ends_on,amount,event_type,status").eq("household_id",householdId).order("starts_on"),sb.from("recurring_transactions").select("id,description,amount,frequency,next_date,ends_on,active,type").eq("household_id",householdId).order("next_date")]);const error=a.error||b.error||c.error;if(error){setMessage(error.message);return}setIncomes((a.data??[]).map(x=>({...x,amount:x.amount===null?null:Number(x.amount)})));setEvents((b.data??[]).map(x=>({...x,amount:x.amount===null?null:Number(x.amount)})));setRecurring((c.data??[]).map(x=>({...x,amount:x.amount===null?null:Number(x.amount)})))},[householdId]);
 useEffect(()=>{queueMicrotask(()=>void load())},[load]);
 useEffect(()=>{if(!householdId)return;const sb=createClient(),refresh=()=>void load();const ch=sb.channel(`calendar-${householdId}`).on("postgres_changes",{event:"*",schema:"public",table:"planned_income",filter:`household_id=eq.${householdId}`},refresh).on("postgres_changes",{event:"*",schema:"public",table:"financial_events",filter:`household_id=eq.${householdId}`},refresh).on("postgres_changes",{event:"*",schema:"public",table:"recurring_transactions",filter:`household_id=eq.${householdId}`},refresh).subscribe();return()=>{void sb.removeChannel(ch)}},[householdId,load]);
 const items=useMemo<Timeline[]>(()=>[...incomes.filter(x=>x.expected_on).map(x=>({id:x.id,kind:"income" as const,title:x.description,amount:x.amount,date:x.expected_on!,status:x.status,subtitle:x.income_class==="extraordinary"?"Receita extraordinária":"Receita prevista",raw:x})),...events.map(x=>({id:x.id,kind:"event" as const,title:x.title,amount:x.amount,date:x.starts_on,status:x.status,subtitle:x.event_type==="bill_due"?"Conta a vencer":"Evento financeiro",raw:x})),...recurring.filter(x=>x.active&&x.next_date).map(x=>({id:x.id,kind:"recurring" as const,title:x.description,amount:x.amount,date:x.next_date!,status:"planned",subtitle:`Recorrência ${frequencyName(x.frequency)}`,raw:x}))].filter(x=>x.date.startsWith(month)).sort((a,b)=>a.date.localeCompare(b.date)),[incomes,events,recurring,month]);
 const pending=items.filter(x=>x.status==="planned"),expected=pending.filter(x=>x.kind==="income").reduce((s,x)=>s+(x.amount||0),0),due=pending.filter(x=>x.kind!=="income").reduce((s,x)=>s+(x.amount||0),0),overdue=pending.filter(x=>x.date<today()).length,next7=pending.filter(x=>{const d=(new Date(`${x.date}T12:00:00`).getTime()-new Date(`${today()}T12:00:00`).getTime())/86400000;return d>=0&&d<=7}).length;
 function move(delta:number){const d=new Date(`${month}-01T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+delta);setMonth(d.toISOString().slice(0,7))}
 async function complete(item:Timeline){const suggested=item.amount?String(item.amount).replace(".",","):"",answer=window.prompt(item.kind==="income"?"Qual valor foi recebido?":"Qual valor foi pago?",suggested);if(answer===null)return;const amount=money(answer);if(!amount||amount<=0){setMessage("Informe um valor válido.");return}setBusy(item.id);const sb=createClient();const result=item.kind==="income"?await sb.rpc("receive_planned_income",{target_income_id:item.id,received_amount:amount,received_on:today()}):item.kind==="recurring"?await sb.rpc("pay_recurring_transaction",{target_recurring_id:item.id,paid_amount:amount,paid_on:today()}):await sb.rpc("complete_financial_event",{target_event_id:item.id,actual_amount:amount,completed_on:today()});setBusy("");setMessage(result.error?result.error.message:item.kind==="income"?"Receita registrada no saldo.":"Pagamento registrado e calendário atualizado.");if(!result.error)await load()}
 async function remove(item:Timeline){if(!window.confirm(`Excluir “${item.title}”?`))return;const table=item.kind==="income"?"planned_income":item.kind==="event"?"financial_events":"recurring_transactions";const {error}=await createClient().from(table).delete().eq("id",item.id).eq("household_id",householdId);setMessage(error?error.message:"Item excluído.");if(!error)await load()}
 return <div className="space-y-5"><div className="flex items-center gap-3"><button onClick={back} className="tap focus-ring grid w-12 place-items-center rounded-2xl bg-white" aria-label="Voltar"><ArrowLeft/></button><div><p className="label">Planejamento</p><h2 className="text-3xl font-black">Calendário financeiro</h2></div></div>
  {message&&<div role="status" className="rounded-2xl bg-mint p-4 text-sm font-bold">{message}</div>}
  <section className="card p-4"><div className="flex items-center justify-between"><button onClick={()=>move(-1)} className="tap grid w-12 place-items-center" aria-label="Mês anterior"><ChevronLeft/></button><div className="text-center"><p className="label">Mês selecionado</p><h3 className="capitalize font-black">{monthLabel(month)}</h3></div><button onClick={()=>move(1)} className="tap grid w-12 place-items-center" aria-label="Próximo mês"><ChevronRight/></button></div><a href="https://calendar.google.com/calendar/u/0/r" target="_blank" rel="noreferrer" className="tap mt-3 flex items-center justify-center gap-2 rounded-xl border border-ink/10 text-sm font-bold"><ExternalLink size={16}/> Abrir Google Calendar da família</a></section>
  <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Summary label="A receber" value={brl(expected)} tone="bg-mint"/><Summary label="A pagar" value={brl(due)} tone="bg-amber-100"/><Summary label="Próximos 7 dias" value={`${next7} itens`} tone="bg-blue-100"/><Summary label="Atrasados" value={`${overdue} itens`} tone={overdue?"bg-red-100":"bg-white"}/></div>
  <div className="grid grid-cols-3 gap-2"><AddButton icon={<TrendingUp/>} label="Receita" on={()=>setForm("income")}/><AddButton icon={<CalendarDays/>} label="Evento" on={()=>setForm("event")}/><AddButton icon={<Repeat2/>} label="Recorrência" on={()=>setForm("recurring")}/></div>
  {form&&<CalendarForm kind={form} householdId={householdId} close={()=>setForm(null)} saved={async()=>{setForm(null);setMessage("Item adicionado ao calendário.");await load()}}/>}
  <section className="card overflow-hidden"><div className="border-b border-ink/10 p-5"><p className="label">Agenda do mês</p><h3 className="mt-1 text-xl font-black">{items.length} compromissos</h3></div>{items.length?<div className="divide-y divide-ink/10">{items.map(item=><article key={`${item.kind}-${item.id}`} className={`p-4 ${item.status!=="planned"?"opacity-55":""}`}><div className="flex gap-3"><div className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl text-center ${item.date<today()&&item.status==="planned"?"bg-red-100":"bg-cream"}`}><b className="text-sm">{dateLabel(item.date).split(" ")[0]}</b><small className="-mt-2 uppercase">{dateLabel(item.date).split(" ")[1]}</small></div><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><div><b className={item.status!=="planned"?"line-through":""}>{item.title}</b><p className="text-xs text-ink/55">{item.subtitle}{item.date<today()&&item.status==="planned"?" · atrasado":""}</p></div>{item.amount!==null&&<strong className="money shrink-0">{item.kind==="income"?"+ ":"− "}{brl(item.amount)}</strong>}</div>{item.status==="planned"?<div className="mt-3 flex gap-2"><button disabled={busy===item.id} onClick={()=>void complete(item)} className="tap flex flex-1 items-center justify-center gap-2 rounded-xl bg-ink px-3 text-xs font-bold text-white disabled:opacity-50"><Check size={15}/>{item.kind==="income"?"Recebi":"Marcar pago"}</button><button onClick={()=>void remove(item)} className="tap grid w-12 place-items-center rounded-xl border border-ink/10" aria-label="Excluir"><Trash2 size={16}/></button></div>:<p className="mt-2 flex items-center gap-1 text-xs font-bold"><Check size={14}/> Concluído</p>}</div></div></article>)}</div>:<div className="p-8 text-center text-ink/55"><CalendarDays className="mx-auto mb-3"/><p>Nenhum compromisso neste mês.</p></div>}</section>
 </div>
}

function CalendarForm({kind,householdId,close,saved}:{kind:Kind;householdId:string;close:()=>void;saved:()=>void}){const [title,setTitle]=useState(""),[amount,setAmount]=useState(""),[date,setDate]=useState(today()),[frequency,setFrequency]=useState("monthly"),[saving,setSaving]=useState(false),[error,setError]=useState("");async function save(){if(!title.trim()||!date){setError("Preencha nome e data.");return}setSaving(true);const sb=createClient(),value=amount?money(amount):null;let result;if(kind==="income")result=await sb.from("planned_income").insert({household_id:householdId,description:title.trim(),amount:value,expected_on:date,income_class:"variable",status:"planned",value_status:value?"confirmed":"to_confirm"});else if(kind==="event")result=await sb.from("financial_events").insert({household_id:householdId,title:title.trim(),amount:value,starts_on:date,event_type:value?"bill_due":"event",status:"planned"});else result=await sb.from("recurring_transactions").insert({household_id:householdId,type:"expense",description:title.trim(),amount:value,frequency,next_date:date,active:true});setSaving(false);if(result.error){setError(result.error.message);return}await saved()}return <section className="card p-5"><div className="flex items-center justify-between"><h3 className="font-black">{kind==="income"?"Nova receita prevista":kind==="event"?"Novo evento ou conta":"Nova conta recorrente"}</h3><button onClick={close} className="tap grid w-12 place-items-center"><X/></button></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Nome</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={kind==="income"?"Ex.: salário ou aluguel":"Ex.: energia ou escola"} className="tap mt-1 w-full rounded-xl border border-ink/15 px-3"/></label><label><span className="label">Valor</span><input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00" className="tap mt-1 w-full rounded-xl border border-ink/15 px-3"/></label><label><span className="label">{kind==="income"?"Data prevista":"Próximo vencimento"}</span><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="tap mt-1 w-full rounded-xl border border-ink/15 px-3"/></label>{kind==="recurring"&&<label className="sm:col-span-2"><span className="label">Frequência</span><select value={frequency} onChange={e=>setFrequency(e.target.value)} className="tap mt-1 w-full rounded-xl border bg-white px-3"><option value="monthly">Mensal</option><option value="weekly">Semanal</option><option value="biweekly">Quinzenal</option><option value="yearly">Anual</option></select></label>}</div>{error&&<p className="mt-3 text-sm font-bold text-red-700">{error}</p>}<button disabled={saving} onClick={()=>void save()} className="tap mt-4 w-full rounded-xl bg-ink p-3 font-bold text-white disabled:opacity-50">{saving?"Salvando…":"Adicionar ao calendário"}</button></section>}
function Summary({label,value,tone}:{label:string;value:string;tone:string}){return <div className={`rounded-2xl p-4 ${tone}`}><p className="text-[10px] font-black uppercase tracking-wide text-ink/55">{label}</p><p className="money mt-1 text-lg font-black">{value}</p></div>}
function AddButton({icon,label,on}:{icon:React.ReactNode;label:string;on:()=>void}){return <button onClick={on} className="tap focus-ring flex flex-col items-center justify-center gap-1 rounded-2xl bg-white p-3 text-xs font-bold shadow-sm"><span className="[&>svg]:h-5">{icon}</span><Plus size={12}/>{label}</button>}
function frequencyName(value:string){return value==="weekly"?"semanal":value==="biweekly"?"quinzenal":value==="yearly"?"anual":"mensal"}
