"use client";

import {useMemo,useState} from "react";
import {ArrowLeft,FileJson,FileSpreadsheet,Mail,ShieldCheck,Target,Users} from "lucide-react";
import {brl,monthStatus} from "@/lib/format";
import {createClient} from "@/lib/supabase/client";

export type SharedTx={id:string,type:"expense"|"income",amount:number,category:string,description:string,person:string,planned:boolean,date:string};
export type Member={id:string,name:string,email:string,role:string};
const REPORT_NOW=Date.parse("2026-09-09T12:00:00Z");

function Header({eyebrow,title,back}:{eyebrow:string,title:string,back:()=>void}){return <div><button onClick={back} className="tap mb-3 flex items-center gap-2 text-sm font-bold"><ArrowLeft size={18}/> Voltar</button><p className="label">{eyebrow}</p><h2 className="text-3xl font-black">{title}</h2></div>}

export function WeeklyReviewPage({back,txs,householdId}:{back:()=>void,txs:SharedTx[],householdId:string}){
 const recent=txs.filter(t=>Date.parse(t.date)>=REPORT_NOW-7*86400000);
 const income=recent.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0),spent=recent.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0),unplanned=recent.filter(t=>t.type==="expense"&&!t.planned).reduce((s,t)=>s+t.amount,0);
 const [couldWait,setCouldWait]=useState(""),[newDebt,setNewDebt]=useState(false),[preserved,setPreserved]=useState(""),[result,setResult]=useState<"good"|"adjust">("good"),[message,setMessage]=useState("");
 async function save(){if(!householdId){setMessage("Família ainda não carregada.");return}const sb=createClient(),{data}=await sb.auth.getUser();const monday=new Date();monday.setDate(monday.getDate()-((monday.getDay()+6)%7));const {error}=await sb.from("weekly_reviews").upsert({household_id:householdId,week_start:monday.toISOString().slice(0,10),could_wait:couldWait,new_debt:newDebt,preserved_amount:Number(preserved.replace(",","."))||0,result,created_by:data.user?.id},{onConflict:"household_id,week_start"});setMessage(error?error.message:"Revisão compartilhada com a família.")}
 return <div className="space-y-5"><Header eyebrow="Fechamento semanal" title="Revisão da Semana" back={back}/><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat l="Receitas" v={brl(income)}/><Stat l="Gastos" v={brl(spent)}/><Stat l="Não planejados" v={brl(unplanned)}/><Stat l="Pode gastar" v={brl(Math.max(3226.58-spent,0))}/></div><section className="card space-y-4 p-5"><label className="block"><span className="label">Alguma compra poderia esperar?</span><textarea value={couldWait} onChange={e=>setCouldWait(e.target.value)} className="mt-2 w-full rounded-xl border p-3" rows={3}/></label><label className="flex items-center justify-between gap-3 rounded-xl bg-cream p-3 font-bold">Criamos alguma dívida nova?<input type="checkbox" checked={newDebt} onChange={e=>setNewDebt(e.target.checked)} className="h-5 w-5"/></label><label className="block"><span className="label">Quanto conseguimos preservar?</span><input value={preserved} onChange={e=>setPreserved(e.target.value)} inputMode="decimal" placeholder="0,00" className="tap mt-2 w-full rounded-xl border px-3"/></label><div className="grid grid-cols-2 gap-2"><button onClick={()=>setResult("good")} className={`tap rounded-xl p-3 font-bold ${result==="good"?"bg-ink text-white":"bg-cream"}`}>Semana boa</button><button onClick={()=>setResult("adjust")} className={`tap rounded-xl p-3 font-bold ${result==="adjust"?"bg-ink text-white":"bg-cream"}`}>Precisamos ajustar</button></div><button onClick={()=>void save()} className="tap w-full rounded-xl bg-lime p-4 font-black">Salvar revisão</button>{message&&<p role="status" className="rounded-xl bg-mint p-3 text-sm">{message}</p>}</section></div>
}

export function GoalsPage({back,householdId}:{back:()=>void,householdId:string}){const [current,setCurrent]=useState(1291.84),[value,setValue]=useState(""),[message,setMessage]=useState("");const pct=Math.min(100,current/3000*100);async function add(){const amount=Number(value.replace(".","").replace(",","."));if(!amount||amount<0)return;const next=current+amount,set=()=>{setCurrent(next);setValue("");setMessage("Aporte registrado na meta.")};if(!householdId){set();return}const sb=createClient();const {data:goal}=await sb.from("financial_goals").select("id").eq("household_id",householdId).eq("active",true).order("created_at").limit(1).maybeSingle();const q=goal?sb.from("financial_goals").update({current_amount:next}).eq("id",goal.id):sb.from("financial_goals").insert({household_id:householdId,name:"Reserva de emergência",target_amount:3000,current_amount:next,active:true});const {error}=await q;if(error)setMessage(error.message);else set()}
 return <div className="space-y-5"><Header eyebrow="Metas e reserva" title="Primeira meta" back={back}/><section className="card p-5"><div className="flex items-center justify-between"><Target/><b>{pct.toFixed(1).replace(".",",")}%</b></div><p className="money mt-4 text-3xl font-black">{brl(current)} <span className="text-base text-ink/45">de {brl(3000)}</span></p><div className="mt-4 h-3 overflow-hidden rounded-full bg-ink/10"><div className="h-full bg-ink" style={{width:`${pct}%`}}/></div><p className="mt-3 text-sm">Faltam <b>{brl(Math.max(3000-current,0))}</b>. FGTS não entra neste cálculo.</p></section><section className="card p-5"><label><span className="label">Adicionar à reserva</span><input value={value} onChange={e=>setValue(e.target.value)} inputMode="decimal" placeholder="R$ 0,00" className="tap mt-2 w-full rounded-xl border px-3"/></label><button onClick={()=>void add()} className="tap mt-3 w-full rounded-xl bg-lime p-4 font-black">Registrar aporte</button>{message&&<p className="mt-3 rounded-xl bg-mint p-3 text-sm">{message}</p>}</section></div>}

export function ReportsPage({back,txs}:{back:()=>void,txs:SharedTx[]}){const [days,setDays]=useState(30);const data=useMemo(()=>txs.filter(t=>Date.parse(t.date)>=REPORT_NOW-days*86400000),[txs,days]);const income=data.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0),spent=data.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0),cats=Object.entries(data.filter(t=>t.type==="expense").reduce<Record<string,number>>((a,t)=>(a[t.category]=(a[t.category]||0)+t.amount,a),{})).sort((a,b)=>b[1]-a[1]);return <div className="space-y-5"><Header eyebrow="Relatórios" title="Visão por período" back={back}/><select value={days} onChange={e=>setDays(Number(e.target.value))} className="tap rounded-xl border bg-white px-4"><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 3 meses</option><option value="365">Últimos 12 meses</option></select><div className="grid grid-cols-2 gap-3"><Stat l="Recebemos" v={brl(income)}/><Stat l="Gastamos" v={brl(spent)}/><Stat l="Resultado" v={brl(income-spent)}/><Stat l="Situação" v={monthStatus(spent,3226.58,Math.min(days,30),30)}/></div><section className="card p-5"><h3 className="font-black">Gastos por categoria</h3><div className="mt-4 space-y-3">{cats.length?cats.map(([name,total])=><div key={name}><div className="flex justify-between text-sm"><b>{name}</b><span>{brl(total)}</span></div><div className="mt-1 h-2 rounded-full bg-ink/10"><div className="h-full rounded-full bg-ink" style={{width:`${spent?total/spent*100:0}%`}}/></div></div>):<p className="text-sm text-ink/55">Nenhum lançamento neste período.</p>}</div></section></div>}

function download(name:string,type:string,content:string){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
export function ExportPage({back,txs}:{back:()=>void,txs:SharedTx[]}){function csv(){const esc=(v:unknown)=>`"${String(v).replaceAll('"','""')}"`;download("orcamento-familia.csv","text/csv;charset=utf-8",["data,tipo,valor,categoria,descricao,registrado_por,planejada",...txs.map(t=>[t.date,t.type,t.amount.toFixed(2),t.category,t.description,t.person,t.planned?"sim":"não"].map(esc).join(","))].join("\n"))}return <div className="space-y-5"><Header eyebrow="Seus dados" title="Exportar e guardar" back={back}/><section className="card divide-y divide-ink/10"><button onClick={csv} className="tap flex w-full gap-4 p-5 text-left"><FileSpreadsheet/><span><b className="block">Baixar planilha CSV</b><small>Abre no Excel e Google Planilhas</small></span></button><button onClick={()=>download("orcamento-familia-backup.json","application/json",JSON.stringify({exported_at:new Date().toISOString(),transactions:txs},null,2))} className="tap flex w-full gap-4 p-5 text-left"><FileJson/><span><b className="block">Baixar backup JSON</b><small>Cópia completa dos lançamentos carregados</small></span></button></section><p className="text-sm text-ink/55">A exportação contém {txs.length} lançamentos atualmente carregados no aplicativo.</p></div>}

export function FamilyPage({back,members,householdId}:{back:()=>void,members:Member[],householdId:string}){const [email,setEmail]=useState(""),[sending,setSending]=useState(false),[message,setMessage]=useState("");async function invite(){if(!email.includes("@")){setMessage("Digite um e-mail válido.");return}setSending(true);const sb=createClient(),{error}=await sb.functions.invoke("invite-family-member",{body:{email,householdId}});setSending(false);if(error){setMessage(error.message);return}setEmail("");setMessage("Convite enviado com segurança.")}return <div className="space-y-5"><Header eyebrow="Família e segurança" title="Membros da família" back={back}/><section className="card divide-y divide-ink/10">{members.map(m=><div key={m.id} className="flex items-center gap-3 p-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-mint"><Users size={18}/></span><div className="flex-1"><b>{m.name}</b><p className="text-xs text-ink/55">{m.email}</p></div><span className="rounded-full bg-cream px-3 py-1 text-xs font-bold">{m.role==="owner"?"Administrador":"Membro"}</span></div>)}</section><section className="card p-5"><div className="flex gap-3"><ShieldCheck/><div><h3 className="font-black">Cadastro público desativado</h3><p className="mt-1 text-sm text-ink/55">Somente pessoas convidadas podem acessar os dados da família.</p></div></div><label className="mt-4 block"><span className="label">E-mail do novo membro</span><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="pessoa@exemplo.com" className="tap mt-2 w-full rounded-xl border px-3"/></label><button disabled={sending||!householdId} onClick={()=>void invite()} className="tap mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-ink p-3 font-bold text-white disabled:opacity-50"><Mail size={18}/>{sending?"Enviando…":"Enviar novo convite"}</button>{message&&<p role="status" className="mt-3 rounded-xl bg-mint p-3 text-sm">{message}</p>}</section></div>}

function Stat({l,v}:{l:string,v:string}){return <div className="card p-4"><p className="label">{l}</p><p className="money mt-2 text-xl font-black">{v}</p></div>}
