"use client";

import {useMemo,useState} from "react";
import {ArrowLeft,Pencil,Search,Trash2} from "lucide-react";
import {brl} from "@/lib/format";

export type TransactionItem={id:string,type:"expense"|"income"|"transfer"|"debt_payment",amount:number,category:string,description:string,person:string,planned:boolean,date:string,cardId?:string,cardName?:string};

const typeLabel={expense:"Despesa",income:"Receita",transfer:"Transferência",debt_payment:"Pagamento de dívida"};

export function TransactionHistory({txs,back,edit,remove}:{txs:TransactionItem[],back:()=>void,edit:(tx:TransactionItem)=>void,remove:(tx:TransactionItem)=>Promise<void>}){
 const [query,setQuery]=useState(""),[type,setType]=useState("all"),[confirmId,setConfirmId]=useState("");
 const rows=useMemo(()=>txs.filter(t=>(type==="all"||t.type===type)&&`${t.description} ${t.category} ${t.person}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)),[txs,query,type]);
 return <div><button onClick={back} className="tap mb-3 flex items-center gap-2 text-sm font-bold"><ArrowLeft size={18}/> Voltar</button><p className="label">Movimentações</p><h2 className="text-3xl font-black">Histórico de lançamentos</h2><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_220px]"><label className="flex items-center gap-2 rounded-xl border bg-white px-3"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar descrição, categoria ou pessoa" className="tap w-full border-0 bg-transparent outline-none"/></label><select value={type} onChange={e=>setType(e.target.value)} className="tap rounded-xl border bg-white px-3"><option value="all">Todos os tipos</option><option value="expense">Despesas</option><option value="income">Receitas</option><option value="transfer">Transferências</option><option value="debt_payment">Pagamentos de dívida</option></select></div><section className="card mt-4 divide-y divide-ink/10">{rows.length?rows.map(t=><article key={t.id} className="p-4"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="truncate">{t.description||t.category||typeLabel[t.type]}</b><span className="rounded-full bg-cream px-2 py-1 text-[10px] font-bold">{typeLabel[t.type]}</span></div><p className="mt-1 text-xs text-ink/55">{new Date(`${t.date}T12:00:00`).toLocaleDateString("pt-BR")} · {t.category||"Sem categoria"} · {t.person}</p></div><p className={`money font-black ${t.type==="income"?"text-emerald-700":""}`}>{t.type==="income"?"+":"−"}{brl(t.amount)}</p></div><div className="mt-3 flex justify-end gap-2"><button onClick={()=>edit(t)} className="tap flex items-center gap-1 rounded-lg border px-3 text-xs font-bold"><Pencil size={14}/> Editar</button>{confirmId===t.id?<><button onClick={()=>setConfirmId("")} className="tap rounded-lg border px-3 text-xs font-bold">Cancelar</button><button onClick={()=>void remove(t)} className="tap rounded-lg bg-red-600 px-3 text-xs font-bold text-white">Confirmar exclusão</button></>:<button onClick={()=>setConfirmId(t.id)} className="tap flex items-center gap-1 rounded-lg border px-3 text-xs font-bold text-red-700"><Trash2 size={14}/> Excluir</button>}</div></article>):<p className="p-6 text-center text-sm text-ink/55">Nenhum lançamento encontrado.</p>}</section></div>
}
