create extension if not exists pgcrypto;
create schema if not exists private;
create type public.member_role as enum ('owner','member');
create type public.value_status as enum ('confirmed','estimated','to_confirm');
create type public.transaction_type as enum ('expense','income','transfer','debt_payment');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, display_name text not null default 'Pessoa', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.households(id uuid primary key default gen_random_uuid(), name text not null default 'Família', initial_seed_applied_at timestamptz, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.household_members(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role public.member_role not null default 'member', created_at timestamptz not null default now(), unique(household_id,user_id));
create table public.household_invites(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, email text not null, token_hash text not null unique, expires_at timestamptz not null, accepted_at timestamptz, created_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.accounts(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, name text not null, kind text not null check(kind in('checking','savings','cash','benefit','reserve','asset')), opening_balance numeric(14,2) not null default 0, available_for_spending boolean not null default true, value_status public.value_status not null default 'confirmed', created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.transaction_categories(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, name text not null, kind text not null check(kind in('expense','income')), active boolean not null default true, created_at timestamptz not null default now(), unique(household_id,name,kind));
create table public.transactions(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, type public.transaction_type not null, amount numeric(14,2) not null check(amount>0), category_id uuid references public.transaction_categories(id), account_id uuid references public.accounts(id), description text, occurred_on date not null default current_date, planned boolean not null default true, is_extraordinary boolean not null default false, extraordinary_destination text, project_id uuid, metadata jsonb not null default '{}', created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.monthly_budgets(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, month date not null, name text not null default 'Orçamento mensal', total_limit numeric(14,2), separate_project boolean not null default false, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(household_id,month,name));
create table public.budget_categories(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, budget_id uuid not null references public.monthly_budgets(id) on delete cascade, category_id uuid not null references public.transaction_categories(id), budgeted numeric(14,2) not null check(budgeted>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(budget_id,category_id));
create table public.credit_cards(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, name text not null, credit_limit numeric(14,2), closing_day int check(closing_day between 1 and 31), due_day int check(due_day between 1 and 31), active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.credit_card_invoices(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, card_id uuid not null references public.credit_cards(id) on delete cascade, closing_date date, due_date date, amount numeric(14,2), status text not null default 'open', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.debts(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, creditor text not null, debt_type text not null, original_amount numeric(14,2), balance numeric(14,2), installment_amount numeric(14,2), total_installments int, current_installment int, rate_reported numeric(9,4), rate_notes text, status text not null, value_status public.value_status not null default 'confirmed', priority text, notes text, last_updated_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.debt_payments(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, debt_id uuid not null references public.debts(id) on delete cascade, transaction_id uuid references public.transactions(id), amount numeric(14,2) not null check(amount>0), paid_on date not null, payroll_deduction boolean not null default false, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table public.financial_goals(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, name text not null, target_amount numeric(14,2), current_amount numeric(14,2) not null default 0, starts_on date, ends_on date, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.recurring_transactions(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, type public.transaction_type not null, description text not null, amount numeric(14,2), category_id uuid references public.transaction_categories(id), frequency text not null, next_date date, ends_on date, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.planned_income(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, description text not null, amount numeric(14,2), expected_on date, income_class text not null check(income_class in('recurring','variable','extraordinary')), status text not null default 'planned', value_status public.value_status not null default 'confirmed', received_transaction_id uuid references public.transactions(id), notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(status<>'received' or received_transaction_id is not null));
create table public.financial_events(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, title text not null, starts_on date not null, ends_on date, amount numeric(14,2), event_type text not null, recurring boolean not null default false, metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.weekly_reviews(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, week_start date not null, could_wait text, new_debt boolean, preserved_amount numeric(14,2), result text check(result in('good','adjust')), created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(household_id,week_start));
create table public.monthly_reviews(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, month date not null, received numeric(14,2) not null default 0, spent numeric(14,2) not null default 0, debt_paid numeric(14,2) not null default 0, saved numeric(14,2) not null default 0, ending_balance numeric(14,2), balance_before_next_income numeric(14,2), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(household_id,month));
create table public.assets(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, name text not null, asset_type text not null, value numeric(14,2), value_status public.value_status not null default 'confirmed', available_for_spending boolean not null default false, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.financial_rules(id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, label text not null, active boolean not null default true, sort_order int not null default 0, created_at timestamptz not null default now());

create index household_members_user_idx on public.household_members(user_id,household_id);
create index transactions_household_date_idx on public.transactions(household_id,occurred_on desc);
create index transactions_category_idx on public.transactions(household_id,category_id,occurred_on);
create index budgets_household_month_idx on public.monthly_budgets(household_id,month);
create index debts_household_status_idx on public.debts(household_id,status);
create index planned_income_household_date_idx on public.planned_income(household_id,expected_on);
create index events_household_date_idx on public.financial_events(household_id,starts_on);

create function private.user_household_ids() returns setof uuid language sql stable security definer set search_path='' as $$ select household_id from public.household_members where user_id=(select auth.uid()) $$;
revoke all on function private.user_household_ids() from public; grant usage on schema private to authenticated; grant execute on function private.user_household_ids() to authenticated;
create function private.is_household_owner(target uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.household_members where household_id=target and user_id=(select auth.uid()) and role='owner') $$;
revoke all on function private.is_household_owner(uuid) from public; grant execute on function private.is_household_owner(uuid) to authenticated;
create function private.is_household_creator(target uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.households where id=target and created_by=(select auth.uid())) $$;
revoke all on function private.is_household_creator(uuid) from public; grant execute on function private.is_household_creator(uuid) to authenticated;

do $$ declare t text; begin foreach t in array array['households','household_members','household_invites','accounts','transaction_categories','transactions','monthly_budgets','budget_categories','credit_cards','credit_card_invoices','debts','debt_payments','financial_goals','recurring_transactions','planned_income','financial_events','weekly_reviews','monthly_reviews','assets','financial_rules'] loop execute format('alter table public.%I enable row level security',t); execute format('revoke all on public.%I from anon, authenticated',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); if t='households' then execute 'create policy household_select on public.households for select to authenticated using(id in(select private.user_household_ids()))'; execute 'create policy household_insert on public.households for insert to authenticated with check(created_by=(select auth.uid()))'; execute 'create policy household_update on public.households for update to authenticated using(private.is_household_owner(id)) with check(private.is_household_owner(id))'; elsif t='household_members' then execute 'create policy members_select on public.household_members for select to authenticated using(household_id in(select private.user_household_ids()))'; execute 'create policy members_insert on public.household_members for insert to authenticated with check(private.is_household_owner(household_id) or (user_id=(select auth.uid()) and private.is_household_creator(household_id)))'; execute 'create policy members_update on public.household_members for update to authenticated using(private.is_household_owner(household_id)) with check(private.is_household_owner(household_id))'; else execute format('create policy %I on public.%I for select to authenticated using(household_id in(select private.user_household_ids()))',t||'_select',t); execute format('create policy %I on public.%I for insert to authenticated with check(household_id in(select private.user_household_ids()))',t||'_insert',t); execute format('create policy %I on public.%I for update to authenticated using(household_id in(select private.user_household_ids())) with check(household_id in(select private.user_household_ids()))',t||'_update',t); execute format('create policy %I on public.%I for delete to authenticated using(household_id in(select private.user_household_ids()))',t||'_delete',t); end if; end loop; end $$;
alter table public.profiles enable row level security; revoke all on public.profiles from anon,authenticated; grant select,insert,update on public.profiles to authenticated;
create policy profile_select on public.profiles for select to authenticated using(id=(select auth.uid()) or id in(select user_id from public.household_members where household_id in(select private.user_household_ids())));
create policy profile_insert on public.profiles for insert to authenticated with check(id=(select auth.uid()));
create policy profile_update on public.profiles for update to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
alter publication supabase_realtime add table public.transactions, public.budget_categories, public.debts;
